
namespace: ecommerce

frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: caramensuachua/ecommerce-frontend
    tag: fcaa81d
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    host: ecommerce.devopsedu.vn
    port: 80


backend:
  enabled: true
  replicaCount: 3
  image:
    repository: caramensuachua/ecommerce-backend
    tag: febc8fa
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: nginx
    host: api-ecommerce.devopsedu.vn
    port: 8080
  secrets:
    MARIADB_DB: ZnVsbC1zdGFjay1lY29tbWVyY2U=
    MARIADB_HOST: ZGF0YWJhc2UtZGUxNTAuYzU0bWFpY3dvODhsLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
    MARIADB_PASSWORD: TnRkMzQyMDAw
    MARIADB_PORT: MzMwNg==
    MARIADB_USERNAME: YWRtaW4=
